### ISSUE TITLE
Tests fail in Windows CI for schema $ref keys

### ISSUE THREAD

**Issue by joelgallant** [launchcodedev/app-config#47]
An example job: https://github.com/launchcodedev/app-config/runs/1481259678

```
FAIL src/schema.test.ts
  ● Schema Loading › References › loads a schema $ref relative to itself

    can't resolve reference C:%5CUsers%5CRUNNER~1%5CAppData%5CLocal%5CTemp%5Ctmp-6372-36J1Vfd5eDZc%5Crootlevel.schema.yml#/Nested from id #

      131 | 
      132 |   describe('References', () => {
    > 133 |     it('loads a schema $ref relative to itself', async () => {
          |     ^
      134 |       await withTempFiles(
      135 |         {
      136 |           'nested-folder/.app-config.schema.yml': `

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/schema.test.ts:133:5)
```

I don't own a Windows OS - help with this would be awesome.

**Comment by joelgallant** [comment]
Note that I think this is entirely because of URI-encoding, which interacts with the windows drive letters.

**Comment by daniel-zarinski** [comment]
I agree the issue seems to stem from URI-encoding.

schema.ts line 155-156: 
```javascript
const resolvedPath = resolve(join(cwd, filepath));
const resolvedPathEncoded = encodeURI(resolvedPath);
```

in macos this returns:
```json
resolvedPath: '/tmp/tmp-2467-LHsjrE3B34fP/rootlevel.schema.yml',
resolvedPathEncoded: '/tmp/tmp-2467-LHsjrE3B34fP/rootlevel.schema.yml',
```

on windows:
```json
resolvedPath: 'C:\\Users\\danie\\AppData\\Local\\Temp\\tmp-11824-yT7IqnmUuekj\\rootlevel.schema.yml',
resolvedPathEncoded: 'C:%5CUsers%5Cdanie%5CAppData%5CLocal%5CTemp%5Ctmp-11824-yT7IqnmUuekj%5Crootlevel.schema.yml',
```

**Comment by joelgallant** [comment]
It might stem from backslashes. Maybe a simple `.replace(/\\/g, '/')` would do it

**Comment by joelgallant** [comment]
New problem is https://github.com/launchcodedev/app-config/runs/1521475748?check_suite_focus=true

Caused by expo-yarn-workspaces.

**Comment by joelgallant** [comment]
Fixed!
